---
# --- Metadatos Básicos ---
title: "Título del Trabajo Final"
author:
   - Mariangel Morales
   - Camila Santiago
  
date: "Abril 16 del 2026"

# --- Metadatos Específicos de Plantilla ---
degree: "Computación I"
director: 
  - Jesus Ochoa 
  - Oliver Triveño
lugar: "Caracas"
facultad: 
  - Facultad de Ciencias Económicas y Sociales
  - Escuela de Estadistica y Ciencias Actuariales
# Ruta al escudo (relativa al archivo .Rmd)
escudo: "Latex/Classes/Escudos/faces"

# --- Bibliografía ---
bibliography: bibliografia.bib

# --- Configuración de Salida ---
output: 
  pdf_document:
    template: template.tex  # Llamamos al archivo de plantilla
    keep_tex: true                 # Útil para ver errores si ocurren
    toc: true                      # Generar índice
    number_sections: true
    citation_package: natbib       # Importante: forzar natbib porque tu plantilla lo usa

# --- Resumen (Abstract) ---
abstract: |
  Resumen del trabajo de investigación...
---

```{r setup, include=FALSE}
# Configuración global de chunks
knitr::opts_chunk$set(
  echo = FALSE,        # Mostrar código
  warning = FALSE,    # Ocultar advertencias
  message = FALSE,    # Ocultar mensajes de carga
  fig.align = "center",
  out.width = "90%",
  fig.pos = "H",
  out.extra = ""
)

# Cargar librerías necesarias
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
library(janitor)

# 1. Carga de data
df <- read.csv("11. Amazon Sales.csv", encoding = "UTF-8")

# 1. Limpieza y selección
df_limpio <- df %>%
  janitor::clean_names() %>%
  select(product_id, product_name, category, actual_price, discount_percentage, discounted_price) %>%
  mutate(
    # Limpiamos los precios con rupias
    actual_price = as.numeric(gsub("[^0-9.]", "", actual_price)),
    discounted_price = as.numeric(gsub("[^0-9.]", "", discounted_price )),
    # Limpiamos los porcentaje
    discount_percentage = as.numeric(gsub("[^0-9.]", "", discount_percentage)) / 100
  )

# 2. Recalculo de %
df_limpio <- df_limpio %>%
  mutate(
    discounted_price = actual_price - (actual_price * discount_percentage),
    discounted_price = round(discounted_price, 0)
  )

# 3. Verificación
head(df_limpio)

# 3. CÁLCULO DE OUTLIERS
Q1 <- quantile(df_limpio$actual_price, 0.25, na.rm = TRUE)
Q3 <- quantile(df_limpio$actual_price, 0.75, na.rm = TRUE)
IQR_val <- Q3 - Q1

limite_inferior <- Q1 - 1.5 * IQR_val
limite_superior <- Q3 + 1.5 * IQR_val

```

\chapter*{Introducción}

Amazon es una multinacional tecnológica estadounidense que ha evolucionado rápidamente desde su creación en 1994. A pesar de su éxito comercial, su amplitud y variedad en el mercado presenta dificultades para los vendedores y compradores. Esta investigación pretende aclarar las dudas relacionadas a los precios, porcentajes de descuento y diferencias de estos entre categorías

\chapter{Planteamiento del Problema}
Amazon es una multinacional tecnológica estadounidense, fundada por Jeff Bezos en 1994, posteriormente, en 1995 se convierte en uno de los primeros grandes minoristas en línea cuando empieza a vender libros de forma online, y en 1996 se expande a la música, el vídeo y otros productos, lanzando su primer sitio web no inglés en Canadá. Durante los 2000 se expande a nuevas categorías de productos, como juguetes y electrónica, y lanza su sitio web en otros idiomas. Amazon sigue creciendo y lanza su programa de afiliación Prime, que ofrece envíos gratuitos ilimitados en dos días para millones de productos, además de otras ventajas exclusivas (2003), así como también, lanza Kindle e-lector y abrir una tienda física en Seattle (2006); su expansión continúa con servicios en la nube, más variedad de productos, sucursales en todo el mundo y Amazon music (2011).  
A pesar de su éxito comercial, su amplitud y variedad en el mercado presenta dificultades para los vendedores, entre ellas, se señala que Amazon tiende a priorizar sus propios productos frente a los de terceros, además del elevado número de negocios que ofrecen otros productos muy similares en la plataforma. Tanto los vendedores independientes como sus competidores comercializan en el mismo escaparate, sin margen de conveniencia para ninguna de las partes. 
La principal virtud de la era digital son los datos. Para las empresas esta es una valiosa información, pero Amazon no comparte estos datos con los vendedores que distribuyen a través de su plataforma. Los vendedores se encargan de llevar a cabo la transacción de los pedidos, pero no pueden acceder a los clientes individualmente. Esto dificulta cualquier intento de fidelización con sus consumidores; así, Amazon  posee el monopolio de los datos, y de las campañas promocionales. 
Un ejemplo desfavorable de esto para los vendedores es la semana del Black Friday, durante las ofertas vigentes, los distribuidores de forma obligatoria tienen que ajustar sus ofertas y sus precios a lo establecido por la plataforma. 
En este marketplace se paga un porcentaje por cada venta que se realice a través de la plataforma,  las comisiones de Amazon se encuentran entre el 7% y el 15% de la venta dependiendo del sector al que pertenezca el artículo. Además, deben pagar al mes o por venta el plan elegido. 
Por esta razón las marcas o negocios que venden productos que tienen un bajo precio necesitan ampliar su catálogo o vender productos de mayor valor para que les sea rentable vender en el marketplace.
\

En este sentido, se plantean las siguientes interrogantes:\


\textbf{1.}	¿Existen categorías donde los descuentos son más altos que el resto del catálogo y, si éstas existen, hay alguna relación entre el precio original y su porcentaje de descuento?\

\textbf{2.}	¿La distribución de los productos está equilibrada entre categorías o, el catálogo es predominante y más voluminoso en otras categorías?\

\textbf{3.}	¿Dentro de las categorías, conviven productos de distintos rangos de precios o existe una homogeneidad entre ellos?\



\section{Justificación}

La presente investigación se justifica por su relevancia práctica y académica. Por la parte práctica, los resultados les van a permitir a los compradores, reconocer ofertas reales y engañosas, y a los vendedores de amazon identificar patrones de descuento y así poder ajustar sus estrategias de precios; y por la parte, de forma académica se aporta una metodología replicable para el análisis de datos de comercio electrónico utilizando python para el dashboard y R para el informe técnico.\

\section{Objetivos}
 
\subsection{Objetivo General}
\begin{itemize}
  \item{Describir la estructura del inventario de Amazon y analizar su estrategia de precios según sus diferentes categorías e identificar las brechas de precios y descuentos entre productos similares.}
\end{itemize}

\subsection{Objetivos Específicos}
\begin{itemize}
  \item{Analizar las diferencias entre productos similares, y la relación de precios entre el precio original y su porcentaje descuento en categorías con precios más altos.}
  \item{Identificar el número de productos existentes en cada categoría para determinar si el catálogo está distribuido equilibradamente o está concentrado en pocas categorías dominantes.}
  \item{Evaluar  la variabilidad de precios dentro de cada categoría para determinar si existen diferencias significativas entre productos de distintos rangos o si hay homogeneidad.}
\end{itemize}


\section{Cobertura}

\subsection{Horizontal}

la cobertura horizontal abarca las variable que identifican cada producto (Id del producto), el nombre asignado del objeto que se está vendiendo (nombre del producto), clasificación del producto (categoría), costo del producto después de aplicar la rebaja (precio con descuento), costo del producto sin ningún descuento (precio actual) y el porcentaje de rebaja aplicado (porcentaje de descuento). 

\

\begin{table}[ht]
\centering
\caption{Variables consideradas} 
\resizebox{10cm}{!} {
\begin{tabular}{ccc}
  \hline
\ \ \ \ \ Id del producto \\ 
  \hline
   Nombre del producto \\ 
Categoría\\ 
Precio con descuento\\
Precio actual\\
Porcentaje de descuento\\
   \hline
\end{tabular}
}
\end{table}

\subsection{Vertical}

La cobertura vertical está comprendida por 1465  registros, que corresponden a productos comercializados en Amazon, cada fila representa un producto con un ID único con sus características, precio, porcentaje de descuento y precio con el descuento.


\section{Periodo de Referencia}

Describir la fuente y el Periodo de Referencia utilizado en el trabajo de investigación

\section{Variables}

Describir la variable en estudio en el trabajo de investigación

\chapter{Marco Teórico}


\section{Bases Teóricas}

Las bases teóricas que se usarán en este trabajo para sustentar el análisis e investigación de este tema son vitales para el entendimiento de la misma, ya que, estas palabras por más “comunes” que puedan sonar, sino se usan en el contexto adecuado pueden dificultar el razonamiento del lector, las siguientes definiciones son:\

\subsection{Catálogo}

Los catálogos son contenedores de elementos que están relacionados entre sí a través de un contexto de negocio \

\subsection{Estrategia de precios }

Enfoque estructurado que las empresas utilizan para determinar cuánto cobrar por sus productos o servicios, se consideran diversos factores, como la demanda del mercado, la competencia, los costos de producción y la percepción de valor por parte del cliente.
 \

\subsection{Marketplace }

Entorno virtual que facilita la compra y venta de productos o servicios entre múltiples vendedores y compradores. Este tipo de plataforma actúa como intermediario, reuniendo a vendedores y consumidores en un solo lugar y ofreciendo una amplia variedad de productos o servicios en una experiencia de compra unificada. \

\subsection{Variabilidad de precios }

Esta variabilidad ayuda a las empresas a gestionar sus ingresos, identifican qué productos contribuyen principalmente a sus beneficios totales y cuáles requieren un enfoque de precios diferente para aumentar los ingresos. \

\subsection{Homogeneidad y heterogeneidad }

La homogeneidad se refiere a elementos semejantes, idénticos e iguales. Por otro lado, la heterogeneidad  se refiere a elementos diferentes, distintos y no equivalentes.
 \

\subsection{Porcentaje de descuento }

Número del descuento que posee el producto. \

\subsection{Varianza  }

Medida de dispersión que representa la variabilidad de una serie de datos con respecto a su media. \

\subsection{Correlación  }

Es la asociación o relación entre dos variables numéricas que evalúa la tendencia (aumento o disminución) en los datos. \

\subsection{Vendedor }

ofrecen productos terminados o servicios a los compradores finales. \

\subsection{Proveedor }

Suministran materias primas o componentes utilizados en la producción. \

\subsection{Comprador }

Es la persona que realiza la transacción de compra, el término comprador suele tener un matiz transaccional, ya que se refiere únicamente a la acción de comprar. \

\chapter{Marco Metódico}
En esta sección se presentan las metodologías y/o test necesarios relacionados con la práctica divulgada en el marco teórico, así como las fuentes de datos.
 
\section{Bases metódicas utilizadas en el trabajo de investigación}

Desarrollo\

\subsection{Item 1}

Descripción\

\subsection{Item 2}

Descripción\

\subsubsection{Item 2.2}

Descripción\

\subsection{Item n}

Descripción\

\chapter{Análisis de Resultados}

{\small Este capítulo presenta los resultados obtenidos al aplicar las metodologías descritas en el capítulo anterior, así como del análisis estadístico descriptivo de las variables estudiadas y las ventajas y desventajas al aplicar dichos tests.}

\section{Presentación de resultados 1}

Descripción\

\section{Presentación de resultados 2}

Descripción\

\section{Presentación de resultados n}

Descripción\

\chapter{Conclusiones y Recomendaciones}

\textbf{1.-} Conclusion 1 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 1 del trabajo de investigación.\

\textbf{2.-} Conclusion 2 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 2 del trabajo de investigación.\

\textbf{n.-} Conclusion n del trabajo de investigación.\

\textbf{Recomendación} Recomendación n del trabajo de investigación.\

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Anexo A}

\chapter{Anexo B}

\chapter{Anexo C}

